use "C:\Users\ujbilgra\OneDrive - Syracuse University\Documents\GitHub\course-project-taxes-tariffs\Reproducibility_Package\Data_Files\sortedultimatemerge.dta"

ttest international, by(id)

ttest consumption, by(id)

*tables generated by stata are not able to be exported fully --> only partial parts of the table which do not show the t-values are able to be exported. Upon further analysis, we are unsure of why this is. Therefore, we manually added the tables into github through the flavored markdown coding 
