*T-Tests.do

*change file path to match yours
cd "C:\Users\kesarrge\OneDrive - Syracuse University\ECN 310\course-project-taxes-tariffs\Reproducibility_Package"

*use data from sortedultimatemerge.dta
use "Data_Files\sortedultimatemerge.dta"

*create a two-sample t test with equal variances
ttest international, by(id)

*create a two-sample t test with equal variances
ttest consumption, by(id)

*tables generated by stata are not able to be exported fully --> only partial parts of the table which do not show the t-values are able to be exported. Upon further analysis, we are unsure of why this is. Therefore, we manually added the tables into github through the flavored markdown coding